### ISSUE TITLE
QA-LSTM and cosine similarity

### ISSUE THREAD

**Issue by rmdort** [sujitpal/dl-models-for-qa#1]
Thanks for the qa models. The paper you are referring to 

https://arxiv.org/pdf/1511.04108.pdf

implements cosine similarity for QA and pairs. In your case, you are actual creating a sum of both question and answer vector

````
model.add(Merge([qenc, aenc], mode="sum"))
````

Does this affect the accuracy? 

The paper also states that the accuracy drops on concatenating q and a pairs

````
Finally, we replace the cosine similarity with a MLP structure, whose input (282x2-dimension) is
the concatenation of question and answer embeddings, and the output is a single similarity score
and test the modified models by a variety of hidden layer size (100,500,1000). We observe that the
modified models not only get >10% accuracy decrease, but also converge much slower
````

**Comment by ynuwm** [comment]
Thanks for the qa models. I have the same confusion~

**Comment by ynuwm** [comment]
maybe the "MLP structure" is too easy.  rather than LSTM(or LSTM-attention) @rmdort

**Comment by sujitpal** [comment]
@rmdort - really sorry about the delay in responding, I must have missed your initial post, saw it when @ynuwm posted on it. To answer your question, a cosine merge basically takes 2 vectors of shape (batch_size, timesteps) and produces a single number. I was trying to build a classifier that could produce a probability distribution over 4 multiple choice answers, so I needed an MLP like thing at the end. 
@ynuwm - it is possible that we can get better results by stacking more LSTMs before finally sending to a MLP output, but since I am trying to do 4 way classification, I think I will need the MLP at the end regardless.

**Comment by sujitpal** [comment]
Sorry, the shape of the vectors should be (batch_size, embedding_size) in my previous comment.
